name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy vires api app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            if [ ! -d "vires-api" ]; then
              mkdir vires-api
            fi
            cd vires-api
            
            if [ ! -d ".git" ]; then
              git clone git@github.com:vchamale/vires-api.git
            else
              git pull origin main
            fi

            cat <<EOF > .env
            PG_USER=${{secrets.PG_USER}}
            PG_HOST=${{secrets.PG_HOST}}
            PG_DATABASE=${{secrets.PG_DATABASE}}
            PG_PASSWORD=${{secrets.PG_PASSWORD}}
            PG_PORT=${{secrets.PG_PORT}}
            JWT_SECRET=${{secrets.JWT_SECRET}}
            EOF

            npm run rebuild:pro

            echo 'Deployment successful to digital ocean'